# Generated by Django 4.0.5 on 2022-06-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_shop', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
